# The MIT License (MIT)
#
# Copyright (c) 2020 Philippe Proulx <pproulx@efficios.com>
#
# Permission is hereby granted, free of charge, to any person obtaining
# a copy of this software and associated documentation files (the
# "Software"), to deal in the Software without restriction, including
# without limitation the rights to use, copy, modify, merge, publish,
# distribute, sublicense, and/or sell copies of the Software, and to
# permit persons to whom the Software is furnished to do so, subject to
# the following conditions:
#
# The above copyright notice and this permission notice shall be
# included in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
# IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY
# CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
# TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
# SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

$schema: http://json-schema.org/draft-07/schema#
$id: https://barectf.org/schemas/2/config/field-type.json
title: Effective field type object
definitions:
  byte-order-prop:
    title: Byte order property value
    oneOf:
      - $ref: https://barectf.org/schemas/2/config/byte-order-prop.json
      - type: 'null'
  align-prop:
    title: Alignment property value
    oneOf:
      - type: integer
        minimum: 1
      - type: 'null'
  encoding-prop:
    title: Encoding property value
    oneOf:
      - type: string
        enum:
        - utf8
        - UTF8
        - utf-8
        - UTF-8
        - Utf-8
        - ascii
        - Ascii
        - ASCII
        - none
        - None
        - NONE
      - type: 'null'
  int-field-type-class-prop:
    type: string
    enum:
      - int
      - integer
  int-field-type:
    title: Integer field type object
    type: object
    properties:
      class:
        $ref: '#/definitions/int-field-type-class-prop'
      size:
        type: integer
        minimum: 1
        maximum: 64
      signed:
        oneOf:
          - type: boolean
          - type: 'null'
      align:
        $ref: '#/definitions/align-prop'
      byte-order:
        $ref: '#/definitions/byte-order-prop'
      base:
        type: string
        oneOf:
          - enum:
            - bin
            - oct
            - dec
            - hex
          - type: 'null'
      encoding:
        $ref: '#/definitions/encoding-prop'
      property-mappings:
        oneOf:
          - type: array
            items:
              type: object
              properties:
                type:
                  type: string
                  const: clock
                name:
                  type: string
                  pattern: '^[A-Za-z_][A-Za-z0-9_]*$'
                property:
                  type: string
                  const: value
              required:
                - type
                - name
                - property
              additionalProperties: false
            minItems: 1
            maxItems: 1
          - type: 'null'
    required:
      - class
      - size
    additionalProperties: false
  float-field-type-class-prop:
    type: string
    enum:
      - flt
      - float
      - floating-point
  float-field-type:
    title: Floating point number field type object
    type: object
    properties:
      class:
        $ref: '#/definitions/float-field-type-class-prop'
      size:
        type: object
        properties:
          exp:
            type: integer
          mant:
            type: integer
        oneOf:
          - properties:
              exp:
                const: 8
              mant:
                const: 24
          - properties:
              exp:
                const: 11
              mant:
                const: 53
        required:
          - exp
          - mant
        additionalProperties: false
      align:
        $ref: '#/definitions/align-prop'
      byte-order:
        $ref: '#/definitions/byte-order-prop'
    required:
      - class
      - size
    additionalProperties: false
  enum-field-type-class-prop:
    type: string
    enum:
      - enum
      - enumeration
  enum-field-type:
    title: Enumeration field type object
    type: object
    properties:
      class:
        $ref: '#/definitions/enum-field-type-class-prop'
      value-type:
        $ref: '#/definitions/int-field-type'
      members:
        type: array
        items:
          anyOf:
            - type: string
            - type: object
              properties:
                label:
                  type: string
                value:
                  oneOf:
                    - type: integer
                    - type: array
                      items:
                        type: integer
                      minItems: 2
                      maxItems: 2
              required:
                - label
                - value
              additionalProperties: false
    required:
      - class
      - value-type
    additionalProperties: false
  string-field-type-class-prop:
    type: string
    enum:
      - str
      - string
  string-field-type:
    title: String field type object
    type: object
    properties:
      class:
        $ref: '#/definitions/string-field-type-class-prop'
      encoding:
        $ref: '#/definitions/encoding-prop'
    required:
      - class
    additionalProperties: false
  array-field-type-class-prop:
    type: string
    const: array
  array-field-type:
    title: Array field type object
    type: object
    properties:
      class:
        $ref: '#/definitions/array-field-type-class-prop'
      element-type:
        $ref: '#/definitions/field-type'
      length:
        type: integer
        minimum: 0
    required:
      - class
      - element-type
      - length
    additionalProperties: false
  struct-field-type-class-prop:
    type: string
    enum:
      - struct
      - structure
  struct-field-type:
    title: Structure field type object
    type: object
    properties:
      class:
        $ref: '#/definitions/struct-field-type-class-prop'
      min-align:
        $ref: '#/definitions/align-prop'
      fields:
        oneOf:
          - type: object
            patternProperties:
              '^[A-Za-z_][A-Za-z0-9_]*$':
                $ref: '#/definitions/field-type'
            additionalProperties: false
          - type: 'null'
    required:
      - class
    additionalProperties: false
  field-type:
    type: object
    properties:
      class:
        enum:
          - int
          - integer
          - flt
          - float
          - floating-point
          - enum
          - enumeration
          - str
          - string
          - array
          - struct
          - structure
    allOf:
      - if:
          properties:
            class:
              $ref: '#/definitions/int-field-type-class-prop'
        then:
          $ref: '#/definitions/int-field-type'
      - if:
          properties:
            class:
              $ref: '#/definitions/float-field-type-class-prop'
        then:
          $ref: '#/definitions/float-field-type'
      - if:
          properties:
            class:
              $ref: '#/definitions/enum-field-type-class-prop'
        then:
          $ref: '#/definitions/enum-field-type'
      - if:
          properties:
            class:
              $ref: '#/definitions/string-field-type-class-prop'
        then:
          $ref: '#/definitions/string-field-type'
      - if:
          properties:
            class:
              $ref: '#/definitions/array-field-type-class-prop'
        then:
          $ref: '#/definitions/array-field-type'
      - if:
          properties:
            class:
              $ref: '#/definitions/struct-field-type-class-prop'
        then:
          $ref: '#/definitions/struct-field-type'
    required:
      - class
$ref: '#/definitions/field-type'
